version: '3.3'
services:
  mysql:
    image: mysql:8.0.26
    ports:
      - 3306:3306
    command: --init-file /data/application/GB-CASHBACK.sql
    volumes:
        - ./database/GB-CASHBACK.sql:/data/application/GB-CASHBACK.sql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  gb-cashback-manager:
    build: ./gb-cashback-manager
    links:
      - mysql
    ports:
      - 9000:9000
    environment:
      - TIMEOUT=${API_TIMEOUT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_LOGGING=${MYSQL_LOGGING}
      - EXTERNAL_CASHBACK_HOST=${EXTERNAL_CASHBACK_HOST}
      - EXTERNAL_CASHBACK_TOKEN=${EXTERNAL_CASHBACK_TOKEN}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    links:
      - mysql
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1