version: '3.3'
services:
  mysql:
    image: mysql:8.0.26
    ports:
      - 3306:3306
    command: --init-file /data/application/GB-CASHBACK.sql
    volumes:
        - ./database/GB-CASHBACK.sql:/data/application/GB-CASHBACK.sql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    links:
      - mysql
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1